name: "Modular infrastructure Deployment - Terraform"

on:
  workflow_call:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: string

jobs:
  oc-cli:
    runs-on: ubuntu-latest


    defaults:
      run:
        shell: bash

    steps:
      - name: Perform an ls
        run: |
          ls -l

      - name: Perform ls -a
        if: ${{ inputs.action == 'destroy' }}
        run: |
          ls -la
