name: Modular Environment Deployment

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: string
        options:
          - deploy
          - destroy
        default: deploy

jobs:
  run-oc:
    uses: ./.github/workflows/cr-mod-template.yaml
    with:
      action: ${{ inputs.action }}
