name: Modular Environment Deployment

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - deploy
          - destroy
        default: deploy
      list_test:
        description: 'Testing an array'
        required: true
        type: string

jobs:
  run-oc:
    uses: ./.github/workflows/cr-mod-template.yaml
    with:
      action: ${{ inputs.action }}
      list_test: ${{ inputs.list_test }}
