name: "Modular infrastructure Deployment - Terraform"

on:
  workflow_call:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: string
      list_test:
        required: true
        type: string

jobs:
  oc-cli:
    runs-on: ubuntu-latest


    defaults:
      run:
        shell: bash

    steps:
      - name: Terraform plan
        if: ${{ inputs.action == 'deploy' }}
        run: |
          echo "Running terraform plan"

      - name: Terraform apply
        if: ${{ inputs.action == 'deploy' }}
        run: |
          echo "Running terraform apply"

      - name: Terraform destoy
        if: ${{ inputs.action == 'destroy' }}
        run: |
          echo "Running terraform destroy"
      - name: Echo Values
        if: ${{ inputs.action == 'deploy' }}
        run: |
          IFS=',' read -ra NAMESPACE_ARRAY <<< "${{ inputs.list_test }}"
          for ns in "${NAMESPACE_ARRAY[@]}"; do
            echo "Echo string: $ns"
            echo "$ns"
          done
        - name: Check if jq is installed
          if: ${{ inputs.action == 'deploy' }}
          run: |
            jq
