name: Output information

on: workflow_dispatch

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      # Here I return some metadata information. This metadata information is collectively named context.
      # GitHub actions creates some context data with various pieces of information about event trigger, about runners, and about other things that can be accessed inside of this steps.
      # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs
      - name: Output GitHub context
        run: echo "${{ toJSON(github) }}"