name: Test project

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      # The ubuntu latest runner already has nodejs installed, but we will install it anyway to see how it works
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:                     # Using with you can configure the action used
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test